MEL4-295 adding client package
melio/vendor-directory-api pull request #37
Opened 2021-04-25 18:59 UTC by shaulzorea

2021-04-26 07:56 UTC, shaikegross commented on packages/client/src/generated-clients/http-client-typescript/.openapi-generator/FILES
> +.openapi-generator-ignore
Whats this file and the VERISON file?

2021-04-26 07:56 UTC, shaikegross commented on packages/client/package.json
> +    "publish": "npm publish",
no need to add publish script. publishing works out of the box with NPM when running `npm publish`

2021-04-26 07:56 UTC, shaikegross commented on packages/client/tsconfig.json
> +    // "declaration": true,                         /* Generates corresponding '.d.ts' file. */
I think this needs to be uncommented so it can be imported in a ts module

2021-04-26 07:56 UTC, shaikegross commented on .gitignore
> +.DS_Store
Add a title? I like when gitignore has titles for what was ignored. like: 

`# mac`
`.DS_Store`

2021-04-26 07:59 UTC, shaikegross requested changes
Hey please uncomment the declaration setting in tsconfig and remove the publish script.

There are some other comments but they aren't "deal breakers"

2021-04-26 19:55 UTC, shaulzorea commented on .gitignore
> +.DS_Store
👍🏽

2021-04-26 19:55 UTC, shaulzorea commented on packages/client/tsconfig.json
> +    // "declaration": true,                         /* Generates corresponding '.d.ts' file. */
👍🏽

2021-04-26 19:55 UTC, shaulzorea commented on packages/client/package.json
> +    "publish": "npm publish",
👍🏽

2021-04-27 07:01 UTC, shaikegross commented on packages/client/src/generated-clients/http-client-typescript/.openapi-generator/FILES
> +.openapi-generator-ignore
hmmm no need to gitignore. my bad

2021-04-27 07:03 UTC, shaikegross approved these changes

2021-04-27 07:04 UTC, merged